# Generated by Django 3.0.8 on 2020-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200722_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[('staff', 'Staff'), ('student', 'Student'), ('teacher', 'Teacher')], default=1, verbose_name='User type'),
        ),
    ]
