# Generated by Django 3.0.8 on 2020-09-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200913_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('dr', 'Dr'), ('prof', 'Professor')], max_length=16, null=True, verbose_name='title'),
        ),
    ]
