# Generated by Django 3.0.8 on 2020-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200729_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
