# Generated by Django 3.0.8 on 2020-08-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200807_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalstage',
            name='courses',
        ),
    ]
