# Generated by Django 3.0.8 on 2020-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_educationalstage_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allow_teacher_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='color',
            field=models.CharField(blank=True, max_length=10, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='school',
            name='enroll_mode',
            field=models.CharField(choices=[('enroll_all', "Enroll to all courses per student's educational stage"), ('choose_to_enroll', 'Choose to enroll to a course')], default='choose_to_enroll', max_length=32, verbose_name='course enroll mode'),
        ),
    ]
