# Generated by Django 3.0.8 on 2020-10-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201006_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalstage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.School'),
        ),
        migrations.AddField(
            model_name='school',
            name='terms_and_privacy',
            field=models.TextField(blank=True),
        ),
    ]
