# Generated by Django 3.0.8 on 2020-10-06 14:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201006_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='support email address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
    ]
