# Generated by Django 3.0.8 on 2020-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201006_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='enroll_mode',
            field=models.CharField(choices=[('enroll_all', "Enroll to all courses per student's educational stage"), ('choose_to_enroll', 'Choose to enroll to a course')], default='enroll_all', max_length=32, verbose_name='course enroll mode'),
        ),
    ]
