# Generated by Django 3.0.8 on 2020-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201006_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='allow_teacher_verification',
            field=models.BooleanField(default=True),
        ),
    ]
