# Generated by Django 3.0.8 on 2020-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201006_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='moto',
            field=models.TextField(blank=True),
        ),
    ]
