# Generated by Django 3.0.8 on 2020-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201006_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='moto',
            field=models.CharField(max_length=256),
        ),
    ]
