# Generated by Django 3.0.8 on 2020-10-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201009_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='copyright_text',
            new_name='footer_text',
        ),
    ]
