[tool.black]
py38 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | */migrations/*.py
  | */*/migrations/*.py
  | */*/*/migrations/*.py

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
