# Generated by Django 3.0.8 on 2020-09-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_auto_20200913_1523'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='classrooms.Classroom', verbose_name='classroom'),
        ),
    ]
