# Generated by Django 3.0.8 on 2020-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color_event',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=10, verbose_name='color'),
        ),
    ]
