# Generated by Django 3.0.8 on 2020-07-29 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enroll_mode', models.CharField(choices=[('all_upon_registation', 'Enroll to all courses upon registration'), ('upon_request', 'Enroll to a course upon request')], default='all_upon_registation', max_length=32, verbose_name='Course enroll mode')),
                ('verify_teacher', models.BooleanField(default=False)),
            ],
        ),
    ]
