# Generated by Django 3.0.8 on 2020-07-21 17:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='country_area',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='country_code',
        ),
        migrations.AddField(
            model_name='billing',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='state',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
