# Generated by Django 3.0.8 on 2020-07-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Event'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_classrooms_classroom_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tags',
            field=models.ManyToManyField(related_name='course_tags', through='classrooms.CourseTag', to='classrooms.Course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('student', 'course')},
        ),
    ]
