# Generated by Django 3.0.8 on 2020-07-22 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_remove_request_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='repeats',
            field=models.CharField(choices=[('never', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('weekday', 'Every Weekday (Mon - Fri)'), ('weekend', 'Every Weekend (Sat - Sun)')], default='never', max_length=32),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
