# Generated by Django 3.0.8 on 2020-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20200811_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text="Duration of the meeting in minutes. Default is 0 (meeting doesn't end).", verbose_name='duration'),
        ),
    ]
