# Generated by Django 3.0.8 on 2020-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_educationalstage_courses'),
        ('classrooms', '0004_auto_20200812_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='educational_stages',
            field=models.ManyToManyField(to='accounts.EducationalStage', verbose_name='educational stages'),
        ),
    ]
