# Generated by Django 3.0.8 on 2020-09-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200813_2241'),
        ('classrooms', '0007_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assistant_teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='assistant_teachers',
            field=models.ManyToManyField(blank=True, related_name='assistant_teachers', to='accounts.Teacher', verbose_name='assistant teachers'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classrooms.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classrooms.Course', verbose_name='course'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('faq', 'Frequently asked questions'), ('announcement', 'Announcements')], default='announcement', max_length=32, verbose_name='category')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classrooms.Course', verbose_name='course')),
            ],
        ),
    ]
