# Generated by Django 3.0.8 on 2020-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_auto_20200903_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='duration',
        ),
    ]
