# Generated by Django 3.0.8 on 2020-09-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_remove_classroom_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Lesson',
        ),
    ]
