# Generated by Django 3.0.8 on 2020-09-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_auto_20200908_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='parent_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.Lesson'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.Post'),
        ),
    ]
