# Generated by Django 3.0.8 on 2020-09-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_auto_20200908_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('faq', 'Frequently Asked Questions (FAQ)'), ('announcement', 'Announcements')], default='announcement', max_length=32, verbose_name='category'),
        ),
    ]
