# Generated by Django 3.0.8 on 2020-09-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0013_auto_20200908_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='classrooms.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='classrooms.Course', verbose_name='course'),
        ),
    ]
