# Generated by Django 3.0.8 on 2020-09-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0014_auto_20200908_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='classrooms.Course', verbose_name='course'),
        ),
    ]
