# Generated by Django 3.0.8 on 2020-09-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20200910_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
    ]
