# Generated by Django 3.0.8 on 2020-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200910_1430'),
        ('classrooms', '0003_lesson_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assistant_teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='assistant_teachers', to='accounts.Teacher', verbose_name='assistant teachers'),
        ),
    ]
