# Generated by Django 3.0.8 on 2020-09-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200913_1523'),
        ('classrooms', '0004_auto_20200910_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assistant_teachers',
            field=models.ManyToManyField(blank=True, related_name='assistant_teachers', to='accounts.Teacher', verbose_name='assistant teachers'),
        ),
        migrations.AlterField(
            model_name='request',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='classrooms.Course'),
        ),
    ]
