# Generated by Django 3.0.8 on 2021-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20210110_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
