# Generated by Django 3.0.8 on 2021-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20210110_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
