# Generated by Django 3.0.8 on 2020-09-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_auto_20200913_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='parent_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_lessons', to='classrooms.Lesson'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_posts', to='classrooms.Post'),
        ),
        migrations.AlterField(
            model_name='request',
            name='classrooms',
            field=models.ManyToManyField(blank=True, help_text='preferred classrooms to join', to='classrooms.Classroom'),
        ),
    ]
